### ISSUE TITLE
Automatic refresh of the token in UserAuthDefaultClient is broken

### ISSUE THREAD

**Issue by dennishall3** [dropbox/dropbox-sdk-rust#88]
**Describe the bug**
The `UserAuthDefaultClient` does not refresh token automatically when getting an `expired_access_token` error.

**Expected Behavior**
The token should be automatically refreshed through `update_token`.

**Actual Behavior**
The first request fails with `{code: 401, status: "Unauthorized", json: "{"error_summary": "expired_access_token...", "error": {".tag": "expired_access_token"}}"}`. Instead of refreshing and retrying the request, it simply fails.

**Versions**
* What version of the SDK are you using? 14.1
* What version of the language are you using? 1.59.0

**Additional context**
After debugging, here is what I found.
The `UserAuthDefaultClient` implements `HttpClient` via the `forward_authed_request` macro. This uses `inner.request` to make the initial request. Then it matches the result of this request with `Error::Authentication(AuthError::ExpiredAccessToken)`. If it matches then it refreshes the token and retry the request.

The issue is that in `inner.request`, `inner` is an `UreqClient`. And the `request` method from the `UreqClient` *does not convert the HTTP error*. It just returns an `UnexpectedHttpError`, no matter what the error is. So the previous match with `Error::Authentication(AuthError::ExpiredAccessToken)` will never be true. The "conversion" to a proper error is made later, within the `client_helper::request_with_body` function, but it is too late.

**Comment by wfraser** [comment]
This should also be fixed by https://github.com/dropbox/dropbox-sdk-rust/pull/143
