### ISSUE TITLE
Access Key not working

### ISSUE THREAD

**Issue by MorphicDreamer** [dropbox/dropbox-sdk-rust#93]
**Before you start**
Have you checked StackOverflow, previous issues, and Dropbox Developer Forums for help? Yes I have checked. This seems to be a problem with Oauth2 and the library's implementation of it.

**What is your question?**
A clear and concise description the question.

Hello, thanks for the library. 

I notice that the access key isn't working. I believe that I have used all of the right methods but I am not sure. I don't know if this is my fault or the libraries fault so I am adding this as "Help". My code generate the url and access token just fine, which tells me that the flow_type and client_id are correct, but the library fails to send the correct information the oath2 servers.

This fails on both PKCE and Authorization code

**Screenshots**
[If applicable, add screenshots to help explain your question.](https://pasteboard.co/xcUg0q2tkxNr.png)

**Versions**
* 0.14.1: library version
* 1.60.0: rust version
* What platform are you using? (if applicable)

**Additional context**
error code: error: Dropbox API returned HTTP 400 Bad Request - {"error": "invalid_grant", "error_description": "code doesn't exist or has expired"}
I am pretty sure this a problem with the library but I can't tell. Thanks for reading!

**Comment by wfraser** [comment]
Sorry but without some code demonstrating the issue there's not much I can do. I did however just recently made a change which reworks the oauth2 code a bit and fixed some bugs; perhaps you can update and try again?
